#server:
#  port: 0
spring:
  application:
    name: pedidos-ms
  datasource:
    url: jdbc:mysql://$DB_HOST:3306/pedido-alurafood?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: $DB_USER
    password: $DB_PASS
    driver-class-name: com.mysql.cj.jdbc.Driver
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${random.int}}