version: '3.8'
services:
  database:
    image: mysql
    container_name: db-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Timaorgs@1910
      - MYSQL_DATABASE=adopet
      - MYSQL_USER=adopet
      - MYSQL_PASSWORD=Timaorgs@1910
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - docker-intranet

networks:
  docker-intranet:
    name: docker-intranet
    driver: bridge