server:
    port: 8084
spring:
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  datasource:
      url: jdbc:postgresql://localhost:5432/pix-consumer
      platform: postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver