server:
    port: 8084
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
      show-sql: true
      format_sql: true
  datasource:
      url: jdbc:postgresql://localhost:5432/pix-consumer
      platform: postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 20000
        maximum-pool-size: 5