server:
  port: 0
spring:
  application:
    name: pagamentos-ms
  datasource:
    url: jdbc:mysql://localhost/pagamento-alurafood?createDatabaseIfNotExist=true&useSSL=false
    username: ${DB_USER_MYSQL}
    password: ${DB_PASSWORD_MYSQL}
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}}
