server:
  port: 0
spring:
  application:
    name: pagamentos-ms
  datasource:
    url: jdbc:mysql://localhost:3306/pagamento-alurafood?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin2024
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}}
resilience4j:
  circuitbreaker:
    instances:
      atualizaPedido:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s
pagamento:
  concluido:
    queue:
      name: pagamento.concluido
  exchange:
    name: pagamento.exchange