spring:
  application:
    name: pagamentos
  datasource:
    url: jdbc:mysql://localhost/pagamento-alurafood?createDatabaseIfNotExist=true&useSSL=false
    username: ${DB_USER_MYSQL}
    password: ${DB_PASSWORD_MYSQL}