server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost/adopet?createDatabaseIfNotExist=true&useSSL=false
    username: ${DB_USER_MYSQL}
    password: ${DB_PASSWORD_MYSQL}
  mail:
    host: smtp.example.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
